config/routes.rb
Rails.application.routes.draw do
  resources :minimeals

  devise_for :users
  resources :foods
  resources :users

  root "foods#index"


  get "homepage" => "foods#index"

end

app/models/food.rb
class Food < ActiveRecord::Base
	has_many :minimeals
end

app/models/minimeal.rb
class Minimeal < ActiveRecord::Base
	belongs_to :user
	belongs_to :food
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :minimeals

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
    	:recoverable, :rememberable, :trackable, :validatable

    def fancy_name
    	username.upcase + "!!!"
    end

    def twitter_profileimage
	    TwitterHelper.getbigprofileimage(username)
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  # add Devise exceptions
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :calories_per_unit, :calories_per_g, :macros_carbs, :macros_protein, :macros_fat)
    end
end

app/controllers/minimeals_controller.rb
class MinimealsController < ApplicationController
  before_action :set_minimeal, only: [:show, :edit, :update, :destroy]

  # GET /minimeals
  # GET /minimeals.json
  def index
    @minimeals = Minimeal.all
    @food = Food.all
  end

  # GET /minimeals/1
  # GET /minimeals/1.json
  def show
  end

  # GET /minimeals/new
  def new
    @minimeal = Minimeal.new
    @food = Food.all
  end

  # GET /minimeals/1/edit
  def edit
  end

  # POST /minimeals
  # POST /minimeals.json
  def create
    # byebug
    @minimeal = Minimeal.new(minimeal_params)
    @minimeal.user_id = current_user.id

    respond_to do |format|
      if @minimeal.save
        format.html { redirect_to minimeals_url, notice: 'Minimeal was successfully created.' }
        format.json { render :show, status: :created, location: @minimeal }
      else
        format.html { render :new }
        format.json { render json: @minimeal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /minimeals/1
  # PATCH/PUT /minimeals/1.json
  def update
    respond_to do |format|
      if @minimeal.update(minimeal_params)
        format.html { redirect_to minimeals_url, notice: 'Minimeal was successfully updated.' }
        format.json { render :show, status: :ok, location: @minimeal }
      else
        format.html { render :edit }
        format.json { render json: @minimeal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /minimeals/1
  # DELETE /minimeals/1.json
  def destroy
    @minimeal.destroy
    respond_to do |format|
      format.html { redirect_to minimeals_url, notice: 'Minimeal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_minimeal
      @minimeal = Minimeal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def minimeal_params
      params.require(:minimeal).permit(:food_id, :grams, :user, :date)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!, only: [:edit, :update]

	def show
		@user = User.find(params[:id])
	end

private
	def user_params

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/minimeals_helper.rb
module MinimealsHelper
end

app/views/foods/_form.html.erb
<div class="large-8 columns">
  <%= form_for(@food) do |f| %>
    <% if @food.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

        <ul>
        <% @food.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :calories_per_unit %><br>
      <%= f.text_field :calories_per_unit %>
    </div>
    <div class="field">
      <%= f.label :calories_per_g %><br>
      <%= f.text_field :calories_per_g %>
    </div>
    <div class="field">
      <%= f.label :macros_carbs %><br>
      <%= f.text_field :macros_carbs %>
    </div>
    <div class="field">
      <%= f.label :macros_protein %><br>
      <%= f.text_field :macros_protein %>
    </div>
    <div class="field">
      <%= f.label :macros_fat %><br>
      <%= f.text_field :macros_fat %>
    </div>
    <div class="actions">
      <%= f.submit :class => ['button', 'radius', 'small'] %>
    </div>
  <% end %>
</div>

app/views/foods/edit.html.erb
<div class="row">
	<div class="large-8 columns">
		<h1>Editing food</h1>
	</div>
</div>

<div class="row">
	<%= render 'form' %>
</div>

<div class="row">
	<div class="large-8 columns">
		<%= link_to 'Show', @food %> |
		<%= link_to 'Back', foods_path %>
	</div>
</div>

app/views/foods/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>Listing foods</h1>
  </div>
</div>


<div class="row">
  <div class="large-12 columns">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Calories per unit</th>
          <th>Calories per g</th>
          <th>Macros carbs</th>
          <th>Macros protein</th>
          <th>Macros fat</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @foods.each do |food| %>
          <tr>
            <td><%= food.name %></td>
            <td><%= food.calories_per_unit %></td>
            <td><%= food.calories_per_g %></td>
            <td><%= food.macros_carbs %></td>
            <td><%= food.macros_protein %></td>
            <td><%= food.macros_fat %></td>
            <td><%= link_to 'Show', food %></td>
            <td><%= link_to 'Edit', edit_food_path(food) %></td>
            <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<br>
<div class="row">
  <div class="large-8 columns">
    <%= link_to 'New Food', new_food_path %>
    <%= link_to 'New minimeal', new_minimeal_path %>

  </div>
</div>

app/views/foods/new.html.erb
<div class="row">
	<div class="large-8 columns">
		<h1>New food</h1>
	</div>
</div>

<div class="row">
	<%= render 'form' %>
</div>

<div class="row">
	<div class="large-8 columns">	
		<%= link_to 'Back', foods_path %>
	</div>
</div>

app/views/foods/show.html.erb
<div class="row">
  <div class="large-8 columns">

    <p id="notice"><%= notice %></p>

    <p>
      <strong>Name:</strong>
      <%= @food.name %>
    </p>

    <p>
      <strong>Calories per unit:</strong>
      <%= @food.calories_per_unit %>
    </p>

    <p>
      <strong>Calories per g:</strong>
      <%= @food.calories_per_g %>
    </p>

    <p>
      <strong>Macros carbs:</strong>
      <%= @food.macros_carbs %>
    </p>

    <p>
      <strong>Macros protein:</strong>
      <%= @food.macros_protein %>
    </p>

    <p>
      <strong>Macros fat:</strong>
      <%= @food.macros_fat %>
    </p>

  </div>
</div>

<div class="row">
  <div class="large-8 columns">
    <%= link_to 'Edit', edit_food_path(@food) %> |
    <%= link_to 'Back', foods_path %>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="row">
  <div class="large-12 columns">
  		<%= link_to 'Homepage', homepage_path %>
   		<%= link_to 'Minimeals', minimeals_path %>
 		

		<% if user_signed_in? %>
			<%= link_to current_user.username.capitalize, user_path(current_user) %>
			<%= link_to 'Log out', destroy_user_session_path, method: :delete %>


		<% else %>	
			<%= link_to 'Login', new_user_session_path %>
			<%= link_to 'Sign up', new_user_registration_path %>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render '/layouts/header' %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/minimeals/_form.html.erb
<div class="large-8 columns">
  <%= form_for(@minimeal) do |f| %>
    <% if @minimeal.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@minimeal.errors.count, "error") %> prohibited this minimeal from being saved:</h2>

        <ul>
        <% @minimeal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :food_id %><br>
      <%= f.select(:food_id, Food.all.collect { |food| [food.name, food.id] }) %>
    </div>

    <div class="field">
      <%= f.label :grams %><br>
      <%= f.text_field :grams %>
    </div>

    <div class="field">
      <%= f.label :date %><br>
      <%= f.date_select :date %>
    </div>

    <div class="actions">
      <%= f.submit :class => ['button', 'radius', 'small'] %>
    </div>
  <% end %>
</div>

app/views/minimeals/edit.html.erb
<h1>Editing minimeal</h1>

<%= render 'form' %>

<%= link_to 'Show', @minimeal %> |
<%= link_to 'Back', minimeals_path %>

app/views/minimeals/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>Listing minimeals</h1>

    <table>
      <thead>
        <tr>
          <th>Food</th>
          <th>Grams</th>
          <th>User</th>
          <th>Date</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @minimeals.each do |minimeal| %>
          <tr>
            <td>  <% if minimeal.food.present? %>
                  <%= link_to minimeal.food.name.capitalize, food_path(minimeal.food.id) %>
                  <% end %>
            </td>
            <td><%= minimeal.grams %></td>
            <td><%= minimeal.user.username.capitalize %></td>
            <td><%= minimeal.date %></td>
            <td><%= link_to 'Show', minimeal %></td>
            <td><%= link_to 'Edit', edit_minimeal_path(minimeal) %></td>
            <td><%= link_to 'Destroy', minimeal, method: :delete, data: { confirm: 'You sure, Jimmy?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<div class="row">
  <div class="large-8 columns">
    <%= link_to 'New Minimeal', new_minimeal_path %>
  </div>
</div>

app/views/minimeals/new.html.erb
<div class="row">
	<div class="large-8 columns">
		<h1>New minimeal</h1>
	</div>
</div>		

<div class="row">
		<%= render 'form' %>
</div>

<div class="row">
	<div class="large-8 columns">	
		<%= link_to 'Back', minimeals_path %>
	</div>
</div>		

app/views/minimeals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Food:</strong>
  <%= @minimeal.food.name %>
</p>

<p>
  <strong>Grams:</strong>
  <%= @minimeal.grams %>
</p>

<p>
  <strong>User:</strong>
  <%= @minimeal.user.username %>
</p>

<p>
  <strong>Date:</strong>
  <%= @minimeal.date %>
</p>

<%= link_to 'Edit', edit_minimeal_path(@minimeal) %> |
<%= link_to 'Back', minimeals_path %>

app/views/users/show.html.erb
<div class="row">
	<div class="large-12 columns">
		<p id="notice"><%= notice %></p>
	</div>
</div>


<div class="row">
	<div class="large-12 columns">
		<p>
		  <strong>Welcome, <%= @user.username.capitalize %>!</strong>
		</p>
		<p>This is what we have been tracking for you these days:</p>
		<p><img src=<%= @user.twitter_profileimage %> alt=""></p>
	</div>
</div>